ACRONYMS = {
    'n': 'número',
    'nº': 'número',
    'nr': 'número',
    'n.º': 'número',
    'n. º': 'número',
    'n.': 'número',

    'art.': 'artigo',
    '§': 'parágrafo',
    '§º': '§',
    '§§': 'parágrafos',
    'inc.': 'inciso',

    '1º': 'primeiro',
    '2º': 'segundo',
    '3º': 'terceiro',
    '4º': 'quarto',
    '5º': 'quinto',
    '6º': 'sexto',
    '7º': 'sétimo',
    '8º': 'oitavo',
    '9º': 'nono',
    '10º': 'décimo',
    '11º': 'décimo primeiro',
    '12º': 'décimo segundo',
    '13º': 'décimo terceiro',
    '14º': 'décimo quarto',
    '15º': 'décimo quinto',
    '16º': 'décimo sexto',
    '17º': 'décimo sétimo',
    '18º': 'décimo oitavo',
    '19º': 'décimo nono',

    '1.º': 'primeiro',
    '2.º': 'segundo',
    '3.º': 'terceiro',
    '4.º': 'quarto',
    '5.º': 'quinto',
    '6.º': 'sexto',
    '7.º': 'sétimo',
    '8.º': 'oitavo',
    '9.º': 'nono',
    '10.º': 'décimo',
    '11.º': 'décimo primeiro',
    '12.º': 'décimo segundo',
    '13.º': 'décimo terceiro',
    '14.º': 'décimo quarto',
    '15.º': 'décimo quinto',
    '16.º': 'décimo sexto',
    '17.º': 'décimo sétimo',
    '18.º': 'décimo oitavo',
    '19.º': 'décimo nono',

    '1,º': 'primeiro',
    '2,º': 'segundo',
    '3,º': 'terceiro',
    '4,º': 'quarto',
    '5,º': 'quinto',
    '6,º': 'sexto',
    '7,º': 'sétimo',
    '8,º': 'oitavo',
    '9,º': 'nono',
    '10,º': 'décimo',
    '11,º': 'décimo primeiro',
    '12,º': 'décimo segundo',
    '13,º': 'décimo terceiro',
    '14,º': 'décimo quarto',
    '15,º': 'décimo quinto',
    '16,º': 'décimo sexto',
    '17,º': 'décimo sétimo',
    '18,º': 'décimo oitavo',
    '19,º': 'décimo nono',

    '1 º': 'primeiro',
    '2 º': 'segundo',
    '3 º': 'terceiro',
    '4 º': 'quarto',
    '5 º': 'quinto',
    '6 º': 'sexto',
    '7 º': 'sétimo',
    '8 º': 'oitavo',
    '9 º': 'nono',
    '10 º': 'décimo',
    '11 º': 'décimo primeiro',
    '12 º': 'décimo segundo',
    '13 º': 'décimo terceiro',
    '14 º': 'décimo quarto',
    '15 º': 'décimo quinto',
    '16 º': 'décimo sexto',
    '17 º': 'décimo sétimo',
    '18 º': 'décimo oitavo',
    '19 º': 'décimo nono',

    '1ª': 'primeira',
    '2ª': 'segunda',
    '3ª': 'terceira',
    '4ª': 'quarta',
    '5ª': 'quinta',
    '6ª': 'sexta',
    '7ª': 'sétima',
    '8ª': 'oitava',
    '9ª': 'nona',
    '10ª': 'décima',
    '11ª': 'décima primeira',
    '12ª': 'décima segunda',
    '13ª': 'décima terceira',
    '14ª': 'décima quarta',
    '15ª': 'décima quinta',
    '16ª': 'décima sexta',
    '17ª': 'décima sétima',
    '18ª': 'décima oitava',
    '19ª': 'décima nona',

    '§.o': 'parágrafo',
    '§1': 'parágrafo primeiro',
    '§1o': 'parágrafo primeiro',
    '§2o': 'parágrafo segundo',
    '§3o': 'parágrafo terceiro',
    '§4o': 'parágrafo quarto',
    '§5o': 'parágrafo quinto',
    '§6o': 'parágrafo sexto',
    '§9o': 'parágrafo nono',
    '§§2o': 'parágrafo segundo',

    '§1º': 'parágrafo primeiro',
    '§2º': 'parágrafo segundo',
    '§3º': 'parágrafo terceiro',
    '§4º': 'parágrafo quarto',
    '§5º': 'parágrafo quinto',
    '§6º': 'parágrafo sexto',
    '§7º': 'parágrafo sétimo',
    '§8º': 'parágrafo oitavo',
    '§9º': 'parágrafo nono',
    '§10º': 'parágrafo décimo',

    '§1': 'parágrafo primeiro',
    '§2': 'parágrafo segundo',
    '§3': 'parágrafo terceiro',
    '§4': 'parágrafo quarto',
    '§5': 'parágrafo quinto',
    '§6': 'parágrafo sexto',
    '§7': 'parágrafo sétimo',
    '§8': 'parágrafo oitavo',
    '§9': 'parágrafo nono',
    '§10': 'parágrafo dez',
    '§11': 'parágrafo onze',
    '§12': 'parágrafo doze',
    '§13': 'parágrafo treze',
    '§14': 'parágrafo quatorze',
    '§15': 'parágrafo quinze',
    '§16': 'parágrafo dezesseis',
    '§17': 'parágrafo dezessete',
    '§18': 'parágrafo dezoito',
    '§19': 'parágrafo dezenove',

    'cf': 'Constituição Federal',
    'cc': 'Código Civil',
    'cpc': 'Código Processo Civil',
    'cpc/15': 'Código Processo Civil',
    'ncpc': 'Código Processo Civil',
    'cpp': 'Código Processo Penal',
    'cp': 'Código Penal',
    'cdc': 'Código Defesa Consumidor',
    'clt': 'Consolidação Leis Trabalho'
}

PUNCTUATIONS = r"""́—’‘«­!"#$%&'()*+:<=>?@[\]^_`{|}~°½º"""
